algoritmo "semnome"
// Função :
// Autor :
// Data : 13/02/2023
// Seção de Declarações 
var
a, b, c, soma : real

inicio

escreval("Escreva o valor de A: ")
leia(a)
escreval("Escreva o valor de B: ")
leia(b)
escreval("Escreva o valor de C: ")
leia(c)

soma<- a + b

SE soma>c ENTAO
escreval("A soma de A e B, são maiores que C")
SENAO
escreval("A soma de A e B, não são maiores que C")
FIMSE



fimalgoritmo

