algoritmo "semnome"
// Função :
// Autor :
// Data : 13/02/2023
// Seção de Declarações
var
a, b, c : real
inicio
escreval("Escreva um número parao A")
leia(a)
escreval("Escreva um valor para o B")
leia(b)
SE a = b  ENTAO
   c<- a + b
   escreval("Os dois números são iguais, logo a soma deles é ",c)
SENAO
   c<- a * b
   escreval("Os dois números não são iguais, logo a multiplicação deles é ",c)
FIMSE
fimalgoritmo
